### ISSUE TITLE
Denial-of-service vulnerability

### ISSUE THREAD

**Issue by KlausTrainer** [KlausTrainer/couch_email_auth#38]
If Bob knows Alice's email address, he could invalidate Alice's authentication cookie by sending an HTTP POST-request that has Alice's email address as `email` parameter value.

The problem is that even when Bob is only pretending to sign in as Alice, by just sending a POST-request containing Alice's email address as `email` parameter value, any authentication cookie that may be in use by Alice is invalidated as well.

**TODOs** (in this order):
- [ ] **test 1**: reproduce the issue
- [ ] **test 2**: proof that the issue is fixed (it must be failing at this point)
- [ ] **bugfix**: test 1 must fail, and test 2 must pass
- [ ] **cleanup**: remove test 1 (which is now obsolete)

**Comment by robertkowalski** [comment]
aw!
